version: '3'

services:
  mariadb:
    build: docker/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tokyo
    volumes:
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf

  workspace:
    tty: true
    build: docker/workspace
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tokyo
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - ./docker/workspace/php.ini:/opt/bitnami/php/conf/php.ini
    # privileged: true # Privileged mode could be required to run this container under Windows
